### ISSUE TITLE
[InformationPopup] Error when Show() called in the ctor of CirclePage

### ISSUE THREAD

**Issue by swift-kim** [Samsung/Tizen.CircularUI#130]
Running the following _CirclePage_ Xaml app failed on the TW2 (Gear S3) target with _InvalidOperationException_.

#### Code
```csharp
public partial class MainPage : CirclePage
{
    private int IncreaseCount = 0;
    private List<byte[]> DummyList = new List<byte[]>();

    public MainPage()
    {
        InitializeComponent();

        var bottomButton = new MenuItem()
        {
            Text = "Go",
            Command = new Command(() =>
            {
                DummyList.Add(new byte[1024 * 1024]);
            })
        };

        var _textButtonPopUp = new InformationPopup();
        _textButtonPopUp.Title = "Increase memory";
        _textButtonPopUp.Text = "Press the button.";
        _textButtonPopUp.BottomButton = bottomButton;

        _textButtonPopUp.BottomButton.Clicked += (s, e) =>
        {
            _textButtonPopUp.Text = $"Num of retries = {++IncreaseCount}";
            _textButtonPopUp.Dismiss();
        };

        _textButtonPopUp.Show();
    }
}
```

#### Logs
```
Unhandled Exception:
System.InvalidOperationException: When the Application's Platform is null, can not show the Dialog.
   at Tizen.Wearable.CircularUI.Forms.Renderer.InformationPopupImplementation.Show()
   at Tizen.Wearable.CircularUI.Forms.InformationPopup.Show()
   at TizenWearableXamlApp1.MainPage..ctor() in TizenWearableXamlApp1\MainPage.xaml.cs:line 39
   at TizenWearableXamlApp1.App..ctor() in TizenWearableXamlApp1\App.xaml.cs:line 19
   at TizenWearableXamlApp1.Program.OnCreate() in TizenWearableXamlApp1\TizenWearableXamlApp1.cs:line 11
   at Tizen.Applications.CoreBackend.UICoreBackend.OnCreateNative(IntPtr data)
   at Tizen.Applications.CoreBackend.UICoreBackend.Run(String[] args)
   at Tizen.Applications.CoreApplication.Run(String[] args)
   at Tizen.Applications.CoreUIApplication.Run(String[] args)
   at TizenWearableXamlApp1.Program.Main(String[] args) in TizenWearableXamlApp1\TizenWearableXamlApp1.cs:line 19
```

I'm wondering if I'm doing something wrong.

**Comment by swift-kim** [comment]
#### Additional information
I was trying the template from Tizen .NET SDK and here is the list of csproj package versions.

#### csproj
```
  <ItemGroup>
    <PackageReference Include="Tizen.NET" Version="5.0.0.14556">
      <ExcludeAssets>Runtime</ExcludeAssets>
    </PackageReference>
    <PackageReference Include="Tizen.NET.Sdk" Version="1.0.1" />
    <PackageReference Include="Tizen.Wearable.CircularUI" Version="1.0.0" />
    <PackageReference Include="Xamarin.Forms" Version="3.2.0.871581" />
  </ItemGroup>
```

**Comment by jkpu** [comment]
InitializeComponent() doesn't mean that app controls are rendered and all resource are ready.
And InformationPopup is not Xamarin control. this is not inherited from xamarin control and not layouted in xamarin page. this control is displayed independently  from xamarin page.

so when device run "_textButtonPopUp.Show();" code. all xamarn renderer resource are not ready. it make exception. If you want to escape this exception. please add this code instead.

 Device.BeginInvokeOnMainThread((Action)(() =>
{
     _textButtonPopUp.Show();
 }));
