### ISSUE TITLE
Some Xaml parser make exception on linked clicked listener in TCListAppender

### ISSUE THREAD

**Issue by idkiller** [Samsung/Tizen.CircularUI#22]
On runtime, TCListAppender makes exception like following
```
Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Xamarin.Forms.Xaml.XamlParseException: Position 27:19. Method DoAdd does not have the correct signature ---> System.ArgumentException: Cannot bind to the target method because its signature or security transparency is not compatible with that of the delegate type.
   at System.Reflection.RuntimeMethodInfo.CreateDelegateInternal(Type delegateType, Object firstArgument, DelegateBindingFlags bindingFlags, StackCrawlMark& stackMark)
   at System.Reflection.RuntimeMethodInfo.CreateDelegate(Type delegateType, Object target)
   at Xamarin.Forms.Xaml.ApplyPropertiesVisitor.TryConnectEvent(Object element, String localName, Boolean attached, Object value, Object rootElement, IXmlLineInfo lineInfo, Exception& exception)
   --- End of inner exception stack trace --- 
   at Xamarin.Forms.Xaml.ApplyPropertiesVisitor.SetPropertyValue(Object xamlelement, XmlName propertyName, Object value, Object rootElement, INode node, HydrationContext context, IXmlLineInfo lineInfo)
   at Xamarin.Forms.Xaml.ApplyPropertiesVisitor.Visit(ValueNode node, INode parentNode)
   at Xamarin.Forms.Xaml.ValueNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
   at Xamarin.Forms.Xaml.ElementNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
   at Xamarin.Forms.Xaml.RootNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
   at Xamarin.Forms.Xaml.XamlLoader.Visit(RootNode rootnode, HydrationContext visitorContext)
   at Xamarin.Forms.Xaml.XamlLoader.Load(Object view, String xaml)
   at Xamarin.Forms.Xaml.XamlLoader.Load(Object view, Type callingType)
   at Xamarin.Forms.Xaml.Extensions.LoadFromXaml[TXaml](TXaml view, Type callingType)
   at WearableUIGallery.TC.TCListAppender.InitializeComponent() in Z:\tizen-src\github\Tizen.CircularUI\test\WearableUIGallery\WearableUIGallery\obj\Debug\netstandard2.0\TC\TCListAppender.xaml.g.cs:line 24
   at WearableUIGallery.TC.TCListAppender..ctor() in Z:\tizen-src\github\Tizen.CircularUI\test\WearableUIGallery\WearableUIGallery\TC\TCListAppender.xaml.cs:line 26
   --- End of inner exception stack trace --- 
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at WearableUIGallery.App.OnItemTapped(Object sender, ItemTappedEventArgs args) in Z:\tizen-src\github\Tizen.CircularUI\test\WearableUIGallery\WearableUIGallery\App.xaml.cs:line 48
   at Xamarin.Forms.ListView.NotifyRowTapped(Int32 groupIndex, Int32 inGroupIndex, Cell cell)
   at Xamarin.Forms.ListView.NotifyRowTapped(Int32 index, Cell cell)
   at Tizen.Wearable.CircularUI.Forms.Renderer.CircleListViewRenderer.OnListViewItemSelected(Object sender, GenListItemEventArgs e) in Z:\tizen-src\github\Tizen.CircularUI\src\Tizen.Wearable.CircularUI.Forms.Renderer\CircleListViewRenderer.cs:line 240 
   at ElmSharp.GenList.<InitializeSmartEvent>b__120_0(Object s, GenListItemEventArgs e)
   at ElmSharp.SmartEvent`1.<>c__DisplayClass12_0.<add_On>b__0(IntPtr d, IntPtr o, IntPtr e)
   at Tizen.Applications.CoreBackend.UICoreBackend.Run(String[] args)
   at Tizen.Applications.CoreApplication.Run(String[] args)
   at Tizen.Applications.CoreUIApplication.Run(String[] args)
   at WearableUIGallery.Tizen.Wearable.Program.Main(String[] args) in Z:\tizen-src\github\Tizen.CircularUI\test\WearableUIGallery\WearableUIGallery.Tizen.Wearable\WearableUIGallery.Tizen.Wearable.cs:line 35
```

It looks a xaml linked incorrect signature Clicked listener makes exception on runtime.

**Comment by idkiller** [comment]
It is fixed with pull request #23
