### ISSUE TITLE
Any project created with CircularUI 1.5.0 prev5 will crash

### ISSUE THREAD

**Issue by axa88** [Samsung/Tizen.CircularUI#287]
**Describe the bug**
Any project created with CircularUI 1.5.0 prev5 will crashes on load.

**To Reproduce**
1. Using VS built in templates, create a default project for Tizen.Net wearable project with no modification (v4 or v5.5 attempted)
2. Replace deprecated  global::Tizen.Wearable.CircularUI.Forms.Renderer.FormsCircularUI.Init();
with Tizen.Wearable.CircularUI.Forms.FormsCircularUI.Init();
3. Launch debug on emulator v4 or 5.5
4. Observe error depending on which version used.  Either failure and hang connecting to debugger, or exception at Forms.Init(app);

**Expected behavior**
App loads and runs...

**Environment (please complete the following information):**
 - Target emulator v4 and v5.5
 - Tizen Platform Version Tizen 4 and 5.5
 - Tizen.CircularUI Version 1.5.0 prev5

**Comment by axa88** [comment]
Result Api4 or 6 run on v4 emulator:
Segmentation fault

![image](https://user-images.githubusercontent.com/13371986/81043034-76012a00-8e7f-11ea-9136-8a4d5d003e55.png)

Result Api4 or 6 run on v5.5 emulator:
unhanded exception

System.TypeLoadException: Could not load type 'Xamarin.Forms.PlatformConfiguration.TizenSpecific.IVideoOutput' from assembly 'Xamarin.Forms.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.Reflection.CustomAttribute._CreateCaObject(RuntimeModule pModule, RuntimeType type, IRuntimeMethodInfo pCtor, Byte** ppBlob, Byte pcNamedArgs)
   at System.Reflection.CustomAttribute.CreateCaObject(RuntimeModule module, RuntimeType type, IRuntimeMethodInfo ctor, IntPtr& blob, IntPtr blobEnd, Int32& namedArgs)
   at System.Reflection.CustomAttribute.AddCustomAttributes(ListBuilder1& attributes, RuntimeModule decoratedModule, Int32 decoratedMetadataToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, ListBuilder1 derivedAttributes)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeAssembly assembly, RuntimeType caType)
   at System.Reflection.RuntimeAssembly.GetCustomAttributes(Type attributeType, Boolean inherit)
   at Xamarin.Forms.Internals.ReflectionExtensions.GetCustomAttributesSafe(Assembly assembly, Type attrType)
   at Xamarin.Forms.Internals.Registrar.RegisterAll(Type[] attrTypes, InitializationFlags flags)
   at Xamarin.Forms.Forms.SetupInit(CoreApplication application, InitializationOptions options)
   at Xamarin.Forms.Forms.Init(CoreApplication application, Boolean useDeviceIndependentPixel)
   at Xamarin.Forms.Forms.Init(CoreApplication application)
   at TizenCircularUi150prev5CrashApi4.Program.Main(String[] args) in C:\Git\axa88\TizenCircularUi150prev5Crash\TizenCircularUi150prev5CrashApi4\TizenCircularUi150prev5CrashApi4.cs:line 17

**Comment by rookiejava** [comment]
This issue has been fixed in CircularUI `1.5.0-pre6`. Thank you for reporting.

**Comment by feduss** [comment]
Same problem with 1.5.2 and last Tizen.net.sdk (6) and 6.0 emulator:

"Could not load type 'Xamarin.Forms.PlatformConfiguration.TizenSpecific.IVideoOutput' from assembly 'Xamarin.Forms.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'."

**Comment by abussl** [comment]
> 
> 
> Same problem with 1.5.2 and last Tizen.net.sdk (6) and 6.0 emulator:
> 
> "Could not load type 'Xamarin.Forms.PlatformConfiguration.TizenSpecific.IVideoOutput' from assembly 'Xamarin.Forms.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'."

I agree. 

See the release notes:
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/release-notes/5.0/5.0.0-api
-> "Removed Type Xamarin.Forms.PlatformConfiguration.TizenSpecific.IVideoOutput"

But Why? 
Still impossible to use XF5 on Tizen.  (Tizen.Net.Sdk/1.1.6).

Notice: It would be better to create a new issue for this problem. This is not the correct thread.
